### ISSUE TITLE
draft.js 부분 모듈화해서 npm 배포 

### ISSUE THREAD

**Issue by HYJ29** [HYJ29/blog_front#32]
d.ts 파일만들어서 타입스크립트 이용할 수있도록 만들어 보기

**Comment by HYJ29** [comment]
만들면서 모듈에 대해서 좀 더 이해하기

**Comment by HYJ29** [comment]
component 도 모듈화 해보기

**Comment by byyoungjin** [comment]
https://github.com/HYJ29/myblog-next 여기서 진행
