### ISSUE TITLE
blog 0.1.1 

### ISSUE THREAD

**Issue by HYJ29** [HYJ29/blog_front#40]
- [x] CSR react 에서 SEO 적용방안? 
[구글 SEO 문서 정독하기](https://developers.google.com/search/docs) 
[react 에서 server side rendering 하는법](https://www.digitalocean.com/community/tutorials/react-server-side-rendering)

meta tag를 통해 
1. 구글 검색 최적화
2. 카카오, 페이스북, 트위터 등 sns 최적화 필요
https://www.youtube.com/watch?v=u-tdYTNJUnU

- [x] 만약 google searching 정도까지 해결이 된다면 유지하고 한계가 분명하다면, 프로젝트 Next.js 로 옮기는것 고려

**Comment by byyoungjin** [comment]
## next.js 로 옮기면서
- [x] SEO 제대로 잡기
- [x] 코드 엉켜있는것들 같이 refactoring 하기
- [x] typescript 적용하기
- [x] DB 도 amplify graphql 이나 firebase 로 옮기는것 고려해 보기 
- [ ] test 정말 간단하게 몇가지 넣어보고, CI/CD 과정에 test 넣기
